namespace MailEase.Providers.Infobip;

public sealed record InfobipMessage : BaseEmailMessage
{
    public string? AmpHtml { get; init; }

    public long? TemplateId { get; init; }

    /// <summary>
    /// The URL on your callback server on which the Delivery report will be sent.
    /// </summary>
    public bool? IntermediateReport { get; init; }

    /// <summary>
    /// The URL on your callback server on which the Delivery report will be sent.
    /// </summary>
    public string? NotifyUrl { get; init; }

    /// <summary>
    /// referred Delivery report content type. Can be (application/json or application/xml)
    /// </summary>
    public string? NotifyContentType { get; init; }

    /// <summary>
    /// Additional client data that will be sent on the notifyUrl.
    /// </summary>
    public object? CallbackData { get; init; }

    /// <summary>
    /// Enable or disable open and click tracking.
    /// Passing true will only enable tracking and the statistics would be visible in the web interface alone.
    /// This can be explicitly overridden by trackClicks and trackOpens.
    /// Defaults to true.
    /// </summary>
    public bool? Track { get; init; }

    /// <summary>
    /// This parameter enables or disables track click feature.
    /// </summary>
    public bool? TrackClicks { get; init; }

    /// <summary>
    /// This parameter enables or disables track open feature.
    /// </summary>
    public bool? TrackOpens { get; init; }

    /// <summary>
    /// The URL on your callback server on which the open and click notifications will be sent. See Tracking Notifications for details.
    /// https://www.infobip.com/docs/email/send-email-over-api#tracking-notifications
    /// </summary>
    public string? TrackingUrl { get; init; }

    /// <summary>
    /// The ID uniquely identifies the sent email request.
    /// This filter will enable you to query delivery reports for all the messages using just one request.
    /// You will receive a bulkId in the response after sending an email request.
    /// If you don't set your own bulkId, unique ID will be generated by our system and returned in the API response.
    /// (Optional Field)
    /// </summary>
    public string? BulkId { get; init; }

    /// <summary>
    /// The ID that uniquely identifies the message sent to a recipient.
    /// (Optional Field)
    /// </summary>
    public string? MessageId { get; init; }

    /// <summary>
    /// General placeholder, given in a form of json example: defaultPlaceholders={"ph1": "Success"},
    /// which will replace given key {{ph1}} with given value Success anywhere in the email (subject, text, html...).
    /// In case of more destinations in To field, this placeholder will resolve the same value for key ph1.
    /// </summary>
    public object? DefaultPlaceholders { get; init; }

    /// <summary>
    /// If set to true, the to recipients will see the list of all other recipients to get the email and the response will return only one messageId.
    /// Otherwise, each recipient will see just their own email and the response will return a unique messageId for each email recipient.
    /// Defaults to false.
    /// </summary>
    public bool? PreserveRecipients { get; init; }

    /// <summary>
    /// Personalize opt out landing page by inserting placeholders. Insert placeholder or tag while designing landing page.
    /// </summary>
    public object? LandingPagePlaceholders { get; init; }

    /// <summary>
    /// The ID of an opt out landing page to be used and displayed once an end user clicks the unsubscribe link.
    /// If not present, default opt out landing page will be displayed.
    /// Create a landing page in your Infobip account and use its ID, e.g., #1_23456
    /// </summary>
    public string? LandingPageId { get; init; }

    /// <summary>
    /// Specifies template language version that will be used in the current message template.
    /// Use version 1 for previous version of template language.
    /// Use version 2 for features of the new template language.
    /// If not present version 1 will be used as default version.
    /// </summary>
    public string? TemplateLanguageVersion { get; init; }

    /// <summary>
    /// Required for application use in a send request for outbound traffic.
    /// Returned in notification events.
    /// </summary>
    public string? ApplicationId { get; init; }

    /// <summary>
    /// Required for entity use in a send request for outbound traffic.
    /// Returned in notification events.
    /// </summary>
    public string? EntityId { get; init; }
}
