name: build

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
    
  pull_request:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  build-library:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set Version
        run: |
          echo $VERSION
          echo ${{ env.VERSION }}

          ASSEMBLY_VERSION=$(echo $VERSION | sed 's/-.*//')
          echo "ASSEMBLY_VERSION=ASSEMBLY_VERSION" >> $GITHUB_ENV
      - name: Set Assembly Version
        run: |
          echo $ASSEMBLY_VERSION
          echo ${{ env.ASSEMBLY_VERSION }}
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release /p:Version=${{ env.$VERSION }} /p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }}
      - name: Test
        run: dotnet test --no-build --no-restore --configuration Release --verbosity normal /p:Version=${{ env.$VERSION }} /p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }}