name: Relase and Publish
on:
  pull_request_target:
    paths-ignore:
      - '.github/workflows/**'
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    if: github.event.pull_request.merged
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get build artifacts from latest workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
      - name: Prepare environment
        run: |
          echo "VERSION=$(cat library/version.txt)" >> $GITHUB_ENV
      - name: Publish to nuget.org
        run: dotnet nuget push library/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Create a new GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          generate_release_notes: true
          files: |
            library/*.nupkg